eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
server:
  port: 3344
spring:
  application:
    name: cloud-config-center
