eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello
          uri: lb://consumer-client
          predicates:
            - Path=/hello/**
            - After=2020-07-03T16:16:59.092+08:00[Asia/Shanghai]
            
        - id: api
          predicates:
            - Path=/api/**
          uri: lb://consumer-client
          
       
