eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test
          uri: lb://consumer-client
          predicates:
            - Path=/hello/test
            - After=2020-07-03T16:16:59.092+08:00[Asia/Shanghai]

        - id: hystrix2
          predicates:
            - Path=/hello/hystrix2
          uri: lb://consumer-client

        - id: person
          predicates:
            - Path=/api/person
          uri: lb://consumer-client
          
        - id: hiddenmessage
          predicates:
            - Path=/api/hiddenmessage
          uri: lb://consumer-client
